Add Android Command Line tools for MacOS images
actions/virtual-environments pull request #2363
Opened 2020-12-28 12:18 UTC by dsame

# Description
New tool 

size:  100Mb
time: 30 secs

Virtual environments currently installs Android "SDK Tools", which is deprecated: https://developer.android.com/studio/releases/sdk-tools

Google suggests using the new "cmdline-tools" package instead:
https://developer.android.com/studio/command-line

#### Related issue: https://github.com/actions/virtual-environments/issues/2252

## Check list
- [x] Related issue / work item is attached
- [x] Tests are written (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

2020-12-29 08:18 UTC, AlenaSviridenko approved these changes

2020-12-29 08:30 UTC, maxim-lobanov approved these changes

2020-12-30 07:38 UTC, miketimofeev requested changes
@dsame the tool is currently installed only for macOS-11 judging by the software output

2020-12-31 08:21 UTC, AlenaSviridenko approved these changes

2020-12-31 08:22 UTC, merged