Document environment variables of linux images
actions/virtual-environments pull request #2498
Opened 2021-01-20 12:37 UTC by dsame

# Description
Improvement

the following environment variables that are mentioned in documentation:

All platforms:
ANDROID_HOME
ANDROID_SDK_ROOT
ANDROID_NDK_HOME
CHROMEWEBDRIVER
EDGEWEBDRIVER
GECKOWEBDRIVER
VCPKG_INSTALLATION_ROOT
CONDA
ANT_HOME
GRADLE_HOME
GOROOT
GOROOT_1_13_X64
GOROOT_1_14_X64
GOROOT_1_15_X64

#### Related issue: https://github.com/actions/virtual-environments/issues/2452

## Check list
- [x] Related issue / work item is attached
- [ ] Changes are tested and related VM images are successfully generated

2021-01-31 22:10 UTC, miketimofeev commented
@dsame @AlenaSviridenko looks like we need to add $GRAALVM_11_ROOT as well
https://github.com/actions/virtual-environments/issues/2197#issuecomment-770459643

2021-02-01 11:15 UTC, maxim-lobanov commented on images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1
> +$markdown += New-MDHeader "Package management environment variables" -Level 4
`Package management environment variables` -> `Environment Variables`

2021-02-03 08:41 UTC, AlenaSviridenko requested changes
No Android env variables and EDGEWEBDRIVER value is empty

2021-02-05 05:03 UTC, maxim-lobanov commented on images/linux/scripts/SoftwareReport/SoftwareReport.Android.psm1
> +    $androidVersions = Get-Item env:ANDROID_*
Could you please sort variables by name?

2021-02-05 05:03 UTC, maxim-lobanov commented on images/linux/scripts/SoftwareReport/SoftwareReport.Browsers.psm1
> +            "Value" = Get-PathWithLink($_.Value)
These variables are not symlinks so we don't need to use `Get-PathWithLink` here

2021-02-05 05:03 UTC, maxim-lobanov commented on images/linux/scripts/SoftwareReport/SoftwareReport.CachedTools.psm1
> +            "Value" = Get-PathWithLink($_.Value)
These variables are not symlinks so we don't need to use `Get-PathWithLink` here

2021-02-05 05:03 UTC, maxim-lobanov commented on images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
> +            "Value" = Get-PathWithLink($_.Value)
These variables are not symlinks so we don't need to use `Get-PathWithLink` here

2021-02-05 05:03 UTC, maxim-lobanov commented on images/linux/scripts/helpers/SoftwareReport.Helpers.psm1
> +    If ($link) {
styling: please use `if` and `else` to be consistent with remain code

2021-02-08 06:39 UTC, maxim-lobanov commented on images/linux/scripts/SoftwareReport/SoftwareReport.CachedTools.psm1
> +function Build-GoEnvironmentTable {
We shouldn't hardcode exact Go versions here. For tool-cache, it is enough to just iterate through all versions in `$toolcachePath = Join-Path $env:AGENT_TOOLSDIRECTORY "Go"`.

See existing function in Windows: https://github.com/actions/virtual-environments/blob/main/images/win/scripts/SoftwareReport/SoftwareReport.CachedTools.psm1#L36

Also, we need to add `arch` property for Go like in Windows

2021-02-08 06:39 UTC, maxim-lobanov commented on images/linux/scripts/SoftwareReport/SoftwareReport.Android.psm1
> +    $shoulddResolveLink = 'ANDROID_NDK_PATH', 'ANDROID_NDK_HOME', 'ANDROID_NDK_ROOT', 'ANDROID_NDK_LATEST_HOME'
nitpick: `shouldResolveLink`

2021-02-10 07:35 UTC, AlenaSviridenko commented on images/linux/scripts/SoftwareReport/SoftwareReport.CachedTools.psm1
> +         "Name" =  "GOROOT"
Probably it makes sense to remove this variable from the report since you will remove it in https://github.com/actions/virtual-environments/pull/2668

2021-02-10 17:40 UTC, AlenaSviridenko commented
empty table for GO

![image](https://user-images.githubusercontent.com/8777209/107548814-286cd700-6be0-11eb-8e73-8744937a7f4a.png)

2021-02-12 07:30 UTC, AlenaSviridenko approved these changes

2021-02-12 07:30 UTC, maxim-lobanov approved these changes

2021-02-12 07:30 UTC, merged