Use default ubuntu repo to install ghc
actions/virtual-environments pull request #3268
Opened 2021-04-26 08:59 UTC by dsame

# Description
Improvement

Remove PPA repo from the apt/sources.list

#### Related issue: https://github.com/actions/virtual-environments-internal/issues/2068
https://github.com/actions/virtual-environments/issues/2951#issuecomment-819658892

## Check list
- [x] Related issue / work item is attached
- [ ] Changes are tested and related VM images are successfully generated

2021-04-26 16:43 UTC, AlenaSviridenko approved these changes

2021-04-26 23:58 UTC, hendis85 requested changes

2021-04-26 23:58 UTC, hendis85 commented on images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
> +    $aptSourceRepo = Get-AptSourceRepository -PackageName "ghc"
images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1

2021-04-27 08:15 UTC, maxim-lobanov approved these changes

2021-04-27 09:24 UTC, miketimofeev approved these changes

2021-04-28 11:51 UTC, merged