[Windows] Rework Kotlin installation
actions/virtual-environments pull request #4083
Opened 2021-09-14 11:22 UTC by dibir-magomedsaygitov

# Description
In scope of this PR we are moving the `Kotlin `installation to a separate file with reworked installation approach. 

#### Related issue: [#4066](https://github.com/actions/virtual-environments/issues/4066)

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

2021-09-14 20:55 UTC, dmitry-shibanov submitted a review, later dismissed

2021-09-15 07:14 UTC, al-cheb commented on images/win/scripts/Installers/Install-Kotlin.ps1
> +$kotlinPath = "C:\Program Files"
Let's use `C:\tools` path for kotlin binaries.

2021-09-15 09:51 UTC, al-cheb approved these changes

2021-09-15 13:16 UTC, vsafonkin submitted a review, later dismissed

2021-09-15 17:05 UTC, MaksimZhukov submitted a review, later dismissed

2021-09-15 19:49 UTC, miketimofeev approved these changes

2021-09-15 19:51 UTC, miketimofeev requested changes
I see no reason to create a new test file for kotlin, let's move the test to the Tools.Tests.ps1 file

2021-09-16 07:43 UTC, dmitry-shibanov approved these changes

2021-09-16 08:12 UTC, miketimofeev approved these changes

2021-09-16 08:13 UTC, al-cheb approved these changes

2021-09-16 08:35 UTC, MaksimZhukov approved these changes

2021-09-16 08:35 UTC, merged

2022-01-26 22:20 UTC, GitesParti343 commented on images/win/toolsets/toolset-2016.json
> -            { "name": "kotlinc" },
kotlinc