[Windows] Add SQL OLEDB Driver to win19 and win22
actions/virtual-environments pull request #4893
Opened 2022-01-17 13:28 UTC by shilovmaksim

# Description
Add SQL OLEDB Driver to win19 and win22

#### Related issue: https://github.com/actions/virtual-environments/issues/4881

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

2022-01-17 14:07 UTC, shilovmaksim commented on images/win/scripts/Installers/Install-SQLOLEDBDriver.ps1
> +Install-Binary -Url $SQLOLEDBDriverUrl -Name $SQLOLEDBDriverName -ArgumentList ("ADDLOCAL=ALL", "IACCEPTMSOLEDBSQLLICENSETERMS=YES", "/qn")
I'm not sure. I used the same approach as in [Install-SQLPowerShellTools.ps1](https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Install-SQLPowerShellTools.ps1).
Could you please advise here?

2022-01-18 04:42 UTC, freddy123098 commented
/azp run windows 2019, windows 2022

2022-01-18 04:43 UTC, freddy123098 commented
@al-cheb can u run the failed ones by using /azp, command

2022-01-18 06:25 UTC, al-cheb commented on images/win/scripts/Tests/Tools.Tests.ps1
> +        "HKLM:\SOFTWARE\Microsoft\MSOLEDBSQL'" | Should -Exist
Remove ' quote

2022-01-18 06:27 UTC, al-cheb commented on images/win/scripts/Installers/Install-SQLOLEDBDriver.ps1
> +Install-Binary -Url $SQLOLEDBDriverUrl -Name $SQLOLEDBDriverName -ArgumentList ("ADDLOCAL=ALL", "IACCEPTMSOLEDBSQLLICENSETERMS=YES", "/qn")
Ok, let's skip.

2022-01-18 06:29 UTC, al-cheb commented on images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
> +    $markdown += (Get-SQLOLEDBDriverVersion)
remove ()

2022-01-18 09:11 UTC, shilovmaksim commented on images/win/scripts/SoftwareReport/SoftwareReport.Generator.ps1
> +    $markdown += (Get-SQLOLEDBDriverVersion)
Done

2022-01-18 09:12 UTC, shilovmaksim commented on images/win/scripts/Tests/Tools.Tests.ps1
> +        "HKLM:\SOFTWARE\Microsoft\MSOLEDBSQL'" | Should -Exist
Done

2022-01-19 13:17 UTC, al-cheb approved these changes

2022-01-19 14:38 UTC, dmitry-shibanov approved these changes

2022-01-19 15:17 UTC, miketimofeev requested changes
Something went wrong
![image](https://user-images.githubusercontent.com/48208649/150159864-8d57739a-8dee-42a8-84b0-f0359740b1c9.png)

2022-01-20 11:13 UTC, shilovmaksim commented
> Something went wrong ![image](https://user-images.githubusercontent.com/48208649/150159864-8d57739a-8dee-42a8-84b0-f0359740b1c9.png)

![image](https://user-images.githubusercontent.com/89912354/150328334-01267b34-360e-482e-a0bc-d87e0311825c.png)

2022-01-20 12:59 UTC, miketimofeev approved these changes

2022-01-20 12:59 UTC, merged