[macOS] Update TCC.db to bypass Microsoft Defender installation
actions/virtual-environments pull request #5018
Opened 2022-02-04 14:46 UTC by maxim-lobanov

# Description
Currently, Microsoft Defender for macOS can't be installed on Hosted Images because of multiple modal approval windows that will block installation.
We would like to pre-approve permission access for `com.microsoft.wdav` app.

## How it works
This PR adds a few more entries to `/Library/Application Support/com.apple.TCC/TCC.db` file via sqlite3:
```
kTCCServiceSystemPolicyAllFiles|com.microsoft.wdav.epsext|0|2|4|1||||UNUSED|||1643970979
kTCCServiceSystemPolicyAllFiles|com.microsoft.wdav|0|2|4|1|NULL|NULL|NULL|'UNUSED'|NULL|0|1643970979
```

## Explanation of fields
```
sqlite > PRAGMA table_info(access)
0|service|TEXT|1||1
1|client|TEXT|1||2
2|client_type|INTEGER|1||3
3|auth_value|INTEGER|1||0
4|auth_reason|INTEGER|1||0
5|auth_version|INTEGER|1||0
6|csreq|BLOB|0||0
7|policy_id|INTEGER|0||0
8|indirect_object_identifier_type|INTEGER|0||0
9|indirect_object_identifier|TEXT|1|'UNUSED'|4
10|indirect_object_code_identity|BLOB|0||0
11|flags|INTEGER|0||0
12|last_modified|INTEGER|1|CAST(strftime('%s','now') AS INTEGER)|0
```

#### Related issue:

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

2022-02-04 15:04 UTC, miketimofeev approved these changes

2022-02-04 16:15 UTC, shadyysf submitted a review, later dismissed

2022-02-07 05:51 UTC, al-cheb approved these changes

2022-02-07 09:20 UTC, MaksimZhukov submitted a review, later dismissed

2022-02-07 09:52 UTC, davidomid requested changes
Sorry to be a pain but is it possible to add comments to these lines so it's clear what they do to someone who doesn't have knowledge of this script without having to look through the Git history? I know it hasn't been done for other lines but I think it would be useful.

2022-02-07 12:29 UTC, MaksimZhukov approved these changes

2022-02-07 12:44 UTC, merged