[macOS] Fix GHCup version output
actions/virtual-environments pull request #5455
Opened 2022-04-29 14:28 UTC by AlexanderGitin

# Description
Fix GHCup version 

#### Related issue:
https://github.com/actions/virtual-environments-internal/issues/3454
## Check list
- [x] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

2022-04-29 14:29 UTC, igorboskovic3 submitted a review, later dismissed

2022-04-29 14:31 UTC, ddobranic approved these changes

2022-04-29 14:49 UTC, al-cheb approved these changes

2022-05-02 08:06 UTC, al-cheb requested changes

2022-05-02 08:06 UTC, al-cheb commented on images/linux/scripts/SoftwareReport/SoftwareReport.Common.psm1
> +    $(ghcup --version) -match "version (?<version>\d+(\.\d+){2,})" | Out-Null
https://github.visualstudio.com/virtual-environments/_build/results?buildId=125094&view=logs&j=80d86624-2c9a-5cad-9434-144b838e69fb&t=0cc083f2-e4b4-5c2b-a1d7-966043ae867c

v - is still there.

![image](https://user-images.githubusercontent.com/47745270/166203423-6440c594-4482-4cd7-a61c-cce7d7a16ed8.png)

2022-05-06 13:00 UTC, al-cheb approved these changes

2022-05-08 06:32 UTC, ddobranic approved these changes

2022-05-08 06:32 UTC, merged